permissions:
  pull-requests: read
steps:
  - uses: actions/checkout@v2
  - uses: ./
    with:
      jiraIssueLabel: dependabot
      jiraProjectKey: TGA
      jiraIssueType: Bug
      githubRepo: dependabot-jira-action
      githubOwner: sprout-tech
    environment:
      JIRA_SUBDOMAIN: ${{ env.JIRA_SUBDOMAIN }}
      JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
